# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='num_casa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa Criadora'),
        ),
    ]
