# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa Criadora')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('periodicidade', models.PositiveIntegerField(verbose_name='Periodicidade')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Id url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AlterField(
            model_name='profissional',
            name='celular',
            field=models.CharField(max_length=11, unique=True, verbose_name='Celular'),
        ),
    ]
