# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171010_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa Criadora')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('periodicidade', models.PositiveIntegerField(verbose_name='Periodicidade')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Custo')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Id url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['nome'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
    ]
