# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171021_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='comissao',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Comissão'),
        ),
    ]
