# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitarAlteracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Solicitante')),
                ('protocolo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo de Atendimento')),
                ('solicitacao', models.CharField(blank=True, choices=[('1', 'Alteração de Plano'), ('2', 'Alterar de Método de Pagamento'), ('3', 'Dúvidas/Críticas/Sugestões'), ('4', 'Cancelar assinatura')], max_length=50, null=True, verbose_name='Solicitação')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('resposta', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fone')),
                ('status', models.CharField(blank=True, choices=[('1', 'Não Atendida'), ('2', 'Atendida')], default='1', max_length=30, null=True, verbose_name='Status Solicitação')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Solicitação de Alteração',
                'verbose_name_plural': 'Solicitações de Alteração',
                'ordering': ['-id'],
            },
        ),
    ]
