# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Vendas'),
        ),
        migrations.AlterField(
            model_name='solicitarpagamento',
            name='plano',
            field=models.CharField(blank=True, choices=[('1', 'Ouro - R$ 119,88/ano'), ('2', 'Prata - R$ 35,97/trimestre'), ('3', 'Bronze - R$ 14,99/mês ')], default='1', max_length=50, null=True, verbose_name='Plano Escolhido'),
        ),
    ]
