# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_auto_20171028_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suporte',
            name='solicitacao',
            field=models.CharField(blank=True, choices=[('1', 'Alteração de Plano'), ('2', 'Regularização de conta'), ('3', 'Alterar de Método de Pagamento'), ('4', 'Dúvidas/ Críticas/ Sugestões'), ('5', 'Cancelar assinatura')], max_length=50, null=True, verbose_name='Solicitação'),
        ),
    ]
