# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20171028_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status de Liberação')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cadastro Vendedor',
                'verbose_name_plural': 'Cadastros Vendedores',
                'ordering': ['status', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='suporte',
            name='solicitacao',
            field=models.CharField(blank=True, choices=[('1', 'Alteração de Plano'), ('2', 'Regularização de conta'), ('3', 'Alterar de Método de Pagamento'), ('4', 'Dúvidas/ Críticas/ Sugestões'), ('5', 'Cancelar assinatura'), ('6', 'Outras')], max_length=50, null=True, verbose_name='Solicitação'),
        ),
    ]
