# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_auto_20171030_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrovendedor',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Aguardando'), ('2', 'Aprovado'), ('3', 'Reprovado')], max_length=30, null=True, verbose_name='Status de Liberação'),
        ),
    ]
