# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0005_auto_20171010_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa Criadora')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Realização')),
                ('periodicidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Periodicidade')),
                ('retorno', models.DateField(blank=True, null=True, verbose_name='Data de Retorno')),
                ('status', models.CharField(choices=[('1', 'Mensagem Enviada'), ('2', 'Mensagem não enviada')], default=2, max_length=3, null=True, verbose_name='Status de Aviso')),
                ('slug', models.SlugField(null=True, verbose_name='ID url')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='registration.Cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='registration.Servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Venda de Serviço',
                'verbose_name_plural': 'Vendas de Serviços',
                'ordering': ['-status', 'retorno'],
            },
        ),
    ]
