# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20171010_1413'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaservico',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='registration.Profissional', verbose_name='Profissional'),
        ),
    ]
