# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171021_2021'),
        ('sale', '0002_vendaservico_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa Criadora')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Realização')),
                ('periodicidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Periodicidade')),
                ('retorno', models.DateField(blank=True, null=True, verbose_name='Data de Retorno')),
                ('status', models.CharField(choices=[('1', 'Mensagem Enviada'), ('2', 'Mensagem não enviada')], default=2, max_length=3, null=True, verbose_name='Status de Aviso')),
                ('slug', models.SlugField(null=True, verbose_name='ID url')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente2', to='registration.Cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='registration.Produto', verbose_name='Produto')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional2', to='registration.Profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Venda de Produto',
                'verbose_name_plural': 'Vendas de Produtos',
                'ordering': ['-status', 'retorno'],
            },
        ),
    ]
