# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_vendaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaproduto',
            name='retorno',
            field=models.DateField(blank=True, null=True, verbose_name='Nova Compra'),
        ),
    ]
