# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20171022_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendaproduto',
            options={'ordering': ['-status', 'nova_compra'], 'verbose_name': 'Venda de Produto', 'verbose_name_plural': 'Vendas de Produtos'},
        ),
    ]
