# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20171028_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='vendaservico',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
