# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_vendaproduto_qtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaservico',
            name='qtd',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
