# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Topo Sistema')),
                ('cor_topo', models.CharField(blank=True, choices=[('1', 'Amarelo (Padrão)'), ('2', 'Vermelho'), ('3', 'Roxo'), ('4', 'Azul')], default='1', max_length=50, null=True, verbose_name='Topo Sistema')),
                ('cor_pn_retorno', models.CharField(blank=True, choices=[('1', 'Amarelo (Padrão)'), ('2', 'Vermelho'), ('3', 'Roxo'), ('4', 'Azul')], default='2', max_length=50, null=True, verbose_name='Topo Sistema')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Design Sistema',
                'verbose_name_plural': 'Designs Sistema',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='dias_aviso',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Avisar em'),
        ),
    ]
