# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171003_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cod_empresa',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Cód Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='plano',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano de Pagamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='ultimo_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissao',
            field=models.CharField(blank=True, default=5, max_length=2, null=True, verbose_name='Nivel Permissão'),
        ),
    ]
