# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_dias_aviso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designsystem',
            options={'verbose_name': 'Design Sistema', 'verbose_name_plural': 'Design Sistema'},
        ),
        migrations.AddField(
            model_name='designsystem',
            name='cor_pn_aniversario',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo (Padrão)'), ('4', 'Azul')], default='3', max_length=50, null=True, verbose_name='Painel de Aniversário'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='cor_pn_retorno',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo (Padrão)'), ('4', 'Azul')], default='3', max_length=50, null=True, verbose_name='Painel de Retorno'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='cor_topo',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo (Padrão)'), ('4', 'Azul')], default='3', max_length=50, null=True, verbose_name='Topo Sistema'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
