# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171004_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsystem',
            name='cor_pn_produto',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo (Padrão)'), ('4', 'Azul')], default='3', max_length=50, null=True, verbose_name='Painel de Produtos'),
        ),
    ]
