# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_designsystem_cor_pn_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ultimo_pagamento',
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='cor_pn_aniversario',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo'), ('4', 'Azul')], default='1', max_length=50, null=True, verbose_name='Painel de Aniversário'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='cor_pn_produto',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo'), ('4', 'Azul')], default='4', max_length=50, null=True, verbose_name='Painel de Produtos'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='cor_pn_retorno',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo'), ('4', 'Azul')], default='2', max_length=50, null=True, verbose_name='Painel de Retorno'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='cor_topo',
            field=models.CharField(blank=True, choices=[('1', 'Amarelo'), ('2', 'Vermelho'), ('3', 'Roxo'), ('4', 'Azul')], default='3', max_length=50, null=True, verbose_name='Topo Sistema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seu Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Nome da Empresa'),
        ),
    ]
