# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171006_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fim_ciclo',
            field=models.DateField(blank=True, null=True, verbose_name='Final do Ciclo'),
        ),
        migrations.AddField(
            model_name='user',
            name='inicio_ciclo',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio do Ciclo'),
        ),
        migrations.AddField(
            model_name='user',
            name='plano',
            field=models.CharField(blank=True, choices=[('1', 'Ouro'), ('2', 'Prata'), ('3', 'Bronze')], max_length=10, null=True, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissao',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Nivel Permissão'),
        ),
    ]
