# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171007_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plano',
            field=models.CharField(blank=True, choices=[('1', 'Ouro'), ('2', 'Prata'), ('3', 'Bronze')], max_length=10, null=True, verbose_name='Plano'),
        ),
    ]
