# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171007_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='status_atendimento',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pagamento',
            new_name='tipo_pagamento',
        ),
    ]
