# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171007_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_atendimento',
            field=models.CharField(blank=True, choices=[('1', 'Não Atendida'), ('2', 'Atendida')], max_length=30, null=True, verbose_name='Status Solicitação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Depósito Bancário'), ('2', 'Boleto')], max_length=50, null=True, verbose_name='Tipo de Pagamento'),
        ),
    ]
