# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171009_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Empresa')),
                ('u_telefone', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Usu - Exibir Telefone?')),
                ('u_data_nascimento', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Usu - Exibir Data de Nascimento?')),
                ('u_endereco', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Usu - Exibir Endereço?')),
                ('p_celular', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Prof - Exibir Celular?')),
                ('p_data_nascimento', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Prof - Exibir Data de Nascimento?')),
                ('p_endereco', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Prof - Exibir Endereço?')),
                ('s_valor', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, verbose_name='Ser - Exibir Valor?')),
                ('s_observacao', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, verbose_name='Ser - Exibir Observação?')),
                ('pr_custo', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Prod - Exibir Custo?')),
                ('pr_valor', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, verbose_name='Prod - Exibir Valor?')),
                ('pr_observacao', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Prod - Exibir Observação?')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Design Sistema',
                'verbose_name_plural': 'Design Sistema',
            },
        ),
    ]
