# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_controlecadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlecadastro',
            options={'verbose_name': 'Controle Cadastro', 'verbose_name_plural': 'Controle Cadastro'},
        ),
    ]
