# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171010_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlecadastro',
            name='u_observacao',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='2', max_length=5, verbose_name='Usu - Exibir Observacao?'),
        ),
    ]
