# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20171011_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigsSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Empresa')),
                ('aviso_retorno', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avisar em')),
                ('aviso_produto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avisar em')),
                ('c_profissional', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, verbose_name='Utilizar Cad Profissional?')),
                ('c_produto', models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, verbose_name='Utilizar Cad Produto?')),
                ('ctrl_servicos', models.CharField(choices=[('1', 'Cadastro'), ('2', 'Utilização')], default='1', max_length=5, verbose_name='Periodicidade Serviços')),
                ('ctrl_produto', models.CharField(choices=[('1', 'Cadastro'), ('2', 'Utilização')], default='2', max_length=5, verbose_name='Periodicidade Produtos')),
            ],
        ),
    ]
