# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_configssistema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configssistema',
            options={'verbose_name': 'Configuração do Sistema', 'verbose_name_plural': 'Configurações do Sistema'},
        ),
        migrations.AddField(
            model_name='configssistema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='configssistema',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='configssistema',
            name='aviso_produto',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Produto - avisar em'),
        ),
        migrations.AlterField(
            model_name='configssistema',
            name='aviso_retorno',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Retorno - avisar em'),
        ),
    ]
