# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20171022_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vendedor',
            field=models.CharField(blank=True, choices=[('0', 'Sem Vendedor'), ('1', 'Edson Pecly'), ('2', 'Graziele Pecly'), ('3', 'Diego Fernando')], default='0', max_length=10, null=True, verbose_name='Vendedor Responsável'),
        ),
    ]
