# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20171022_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Confirmado?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Nova Senha',
                'verbose_name_plural': 'Novas Senhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='configssistema',
            name='c_produto',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, null=True, verbose_name='Utilizar Cad Produto?'),
        ),
        migrations.AlterField(
            model_name='configssistema',
            name='c_profissional',
            field=models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, null=True, verbose_name='Utilizar Cad Profissional?'),
        ),
        migrations.AlterField(
            model_name='configssistema',
            name='ctrl_produto',
            field=models.CharField(blank=True, choices=[('1', 'Cadastro'), ('2', 'Utilização')], default='2', max_length=5, null=True, verbose_name='Periodicidade Produtos'),
        ),
        migrations.AlterField(
            model_name='configssistema',
            name='ctrl_servicos',
            field=models.CharField(blank=True, choices=[('1', 'Cadastro'), ('2', 'Utilização')], default='1', max_length=5, null=True, verbose_name='Periodicidade Serviços'),
        ),
    ]
