# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171021_2021'),
        ('core', '0025_auto_20171022_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicidadeProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_produto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Periodicidade Clinte - Produto')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_cliente_produto', to='registration.Cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_produto', to='registration.Produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Periodicidade Cliente Produto',
                'verbose_name_plural': 'Periodicidades Clientes Produtos',
            },
        ),
        migrations.AlterField(
            model_name='controlecadastro',
            name='u_data_nascimento',
            field=models.CharField(choices=[('1', 'Sim'), ('2', 'Não')], default='1', max_length=5, verbose_name='Usu - Exibir Data de Nascimento?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='WhatsApp'),
        ),
    ]
