# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20171021_2021'),
        ('core', '0026_auto_20171026_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicidadeServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_servico', models.PositiveIntegerField(blank=True, null=True, verbose_name='Periodicidade Cliente - Serviço')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_cliente_servico', to='registration.Cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_servico', to='registration.Servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Consumo Cliente Servico',
                'verbose_name_plural': 'Consumos Clientes Servicos',
            },
        ),
        migrations.AlterModelOptions(
            name='periodicidadeproduto',
            options={'verbose_name': 'Consumo Cliente Produto', 'verbose_name_plural': 'Consumos Clientes Produtos'},
        ),
        migrations.AlterField(
            model_name='periodicidadeproduto',
            name='pc_produto',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Periodicidade Cliente - Produto'),
        ),
    ]
