# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20171028_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nivel Permissão'),
        ),
    ]
