# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20171028_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plano',
            field=models.CharField(blank=True, choices=[('1', 'Ouro - R$ 119,88/ano'), ('2', 'Prata - R$ 35,97/trimestre'), ('3', 'Bronze - R$ 14,99/mês ')], max_length=10, null=True, verbose_name='Plano'),
        ),
    ]
